### ISSUE TITLE
RuntimeException: No locale bundles are available

### ISSUE THREAD

**Issue by Om-i** [LogisimIt/Logisim#32]
I run java version 1.8.0_261

I double click on Logisim-ITA.exe and it doesn't run.
I tried to run the jar file in cmd and this stack trace appears:
```
>java -jar Logisim-ITA.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.cburch.logisim.data.Direction.<clinit>(Direction.java:9)
        at com.cburch.logisim.prefs.AppPreferences.<clinit>(AppPreferences.java:163)
        at com.cburch.logisim.gui.start.Startup.parseArgs(Startup.java:114)
        at com.cburch.logisim.Main.main(Main.java:60)
Caused by: java.lang.RuntimeException: No locale bundles are available
        at com.cburch.logisim.util.LocaleManager.loadDefault(LocaleManager.java:293)
        at com.cburch.logisim.util.LocaleManager.<init>(LocaleManager.java:186)
        at com.cburch.logisim.data.Strings.<clinit>(Strings.java:10)
        ... 4 more
```
Do you have any idea what is this?
It happens as well with logisim-win-2.7.1.exe downloaded from cburch.com

Thank You

**Comment by Om-i** [comment]
Apparently it was a permission issue, I moved the folder from the desktop to C:\ an now it works.
